[programs.localnet]
jobtest = "C7HCPK2QPewTvmUVcdhP9KkutKF1pEriWm4RBtYr6pYL"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/kingsley/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
